// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: chargingCmd.proto
// Protobuf Java Version: 4.28.3

package com.easyit.SmartChargeStation.protocol.protobuf;

public final class ChargingCmdProtobuf {
  private ChargingCmdProtobuf() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      ChargingCmdProtobuf.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ChargingCmdOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ChargingCmd)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string cmd = 1;</code>
     * @return The cmd.
     */
    String getCmd();
    /**
     * <code>string cmd = 1;</code>
     * @return The bytes for cmd.
     */
    com.google.protobuf.ByteString
        getCmdBytes();

    /**
     * <code>string piles = 2;</code>
     * @return The piles.
     */
    String getPiles();
    /**
     * <code>string piles = 2;</code>
     * @return The bytes for piles.
     */
    com.google.protobuf.ByteString
        getPilesBytes();

    /**
     * <code>string opid = 3;</code>
     * @return The opid.
     */
    String getOpid();
    /**
     * <code>string opid = 3;</code>
     * @return The bytes for opid.
     */
    com.google.protobuf.ByteString
        getOpidBytes();
  }
  /**
   * <pre>
   * 定义充电指令的消息类型
   * </pre>
   *
   * Protobuf type {@code ChargingCmd}
   */
  public static final class ChargingCmd extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:ChargingCmd)
      ChargingCmdOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 3,
        /* suffix= */ "",
        ChargingCmd.class.getName());
    }
    // Use ChargingCmd.newBuilder() to construct.
    private ChargingCmd(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ChargingCmd() {
      cmd_ = "";
      piles_ = "";
      opid_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ChargingCmdProtobuf.internal_static_ChargingCmd_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ChargingCmdProtobuf.internal_static_ChargingCmd_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ChargingCmd.class, Builder.class);
    }

    public static final int CMD_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile Object cmd_ = "";
    /**
     * <code>string cmd = 1;</code>
     * @return The cmd.
     */
    @Override
    public String getCmd() {
      Object ref = cmd_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        cmd_ = s;
        return s;
      }
    }
    /**
     * <code>string cmd = 1;</code>
     * @return The bytes for cmd.
     */
    @Override
    public com.google.protobuf.ByteString
        getCmdBytes() {
      Object ref = cmd_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        cmd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PILES_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile Object piles_ = "";
    /**
     * <code>string piles = 2;</code>
     * @return The piles.
     */
    @Override
    public String getPiles() {
      Object ref = piles_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        piles_ = s;
        return s;
      }
    }
    /**
     * <code>string piles = 2;</code>
     * @return The bytes for piles.
     */
    @Override
    public com.google.protobuf.ByteString
        getPilesBytes() {
      Object ref = piles_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        piles_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OPID_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile Object opid_ = "";
    /**
     * <code>string opid = 3;</code>
     * @return The opid.
     */
    @Override
    public String getOpid() {
      Object ref = opid_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        opid_ = s;
        return s;
      }
    }
    /**
     * <code>string opid = 3;</code>
     * @return The bytes for opid.
     */
    @Override
    public com.google.protobuf.ByteString
        getOpidBytes() {
      Object ref = opid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        opid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(cmd_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, cmd_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(piles_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, piles_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(opid_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, opid_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(cmd_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, cmd_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(piles_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, piles_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(opid_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, opid_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ChargingCmd)) {
        return super.equals(obj);
      }
      ChargingCmd other = (ChargingCmd) obj;

      if (!getCmd()
          .equals(other.getCmd())) return false;
      if (!getPiles()
          .equals(other.getPiles())) return false;
      if (!getOpid()
          .equals(other.getOpid())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CMD_FIELD_NUMBER;
      hash = (53 * hash) + getCmd().hashCode();
      hash = (37 * hash) + PILES_FIELD_NUMBER;
      hash = (53 * hash) + getPiles().hashCode();
      hash = (37 * hash) + OPID_FIELD_NUMBER;
      hash = (53 * hash) + getOpid().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ChargingCmd parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ChargingCmd parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ChargingCmd parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ChargingCmd parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ChargingCmd parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ChargingCmd parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ChargingCmd parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static ChargingCmd parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ChargingCmd parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static ChargingCmd parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ChargingCmd parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static ChargingCmd parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ChargingCmd prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 定义充电指令的消息类型
     * </pre>
     *
     * Protobuf type {@code ChargingCmd}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ChargingCmd)
        ChargingCmdOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ChargingCmdProtobuf.internal_static_ChargingCmd_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ChargingCmdProtobuf.internal_static_ChargingCmd_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ChargingCmd.class, Builder.class);
      }

      // Construct using com.easyit.SmartChargeStation.protocol.protobuf.ChargingCmdProtobuf.ChargingCmd.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        cmd_ = "";
        piles_ = "";
        opid_ = "";
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ChargingCmdProtobuf.internal_static_ChargingCmd_descriptor;
      }

      @Override
      public ChargingCmd getDefaultInstanceForType() {
        return ChargingCmd.getDefaultInstance();
      }

      @Override
      public ChargingCmd build() {
        ChargingCmd result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public ChargingCmd buildPartial() {
        ChargingCmd result = new ChargingCmd(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(ChargingCmd result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.cmd_ = cmd_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.piles_ = piles_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.opid_ = opid_;
        }
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ChargingCmd) {
          return mergeFrom((ChargingCmd)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ChargingCmd other) {
        if (other == ChargingCmd.getDefaultInstance()) return this;
        if (!other.getCmd().isEmpty()) {
          cmd_ = other.cmd_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getPiles().isEmpty()) {
          piles_ = other.piles_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getOpid().isEmpty()) {
          opid_ = other.opid_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                cmd_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                piles_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                opid_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private Object cmd_ = "";
      /**
       * <code>string cmd = 1;</code>
       * @return The cmd.
       */
      public String getCmd() {
        Object ref = cmd_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          cmd_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string cmd = 1;</code>
       * @return The bytes for cmd.
       */
      public com.google.protobuf.ByteString
          getCmdBytes() {
        Object ref = cmd_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          cmd_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cmd = 1;</code>
       * @param value The cmd to set.
       * @return This builder for chaining.
       */
      public Builder setCmd(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        cmd_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string cmd = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCmd() {
        cmd_ = getDefaultInstance().getCmd();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string cmd = 1;</code>
       * @param value The bytes for cmd to set.
       * @return This builder for chaining.
       */
      public Builder setCmdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        cmd_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private Object piles_ = "";
      /**
       * <code>string piles = 2;</code>
       * @return The piles.
       */
      public String getPiles() {
        Object ref = piles_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          piles_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string piles = 2;</code>
       * @return The bytes for piles.
       */
      public com.google.protobuf.ByteString
          getPilesBytes() {
        Object ref = piles_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          piles_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string piles = 2;</code>
       * @param value The piles to set.
       * @return This builder for chaining.
       */
      public Builder setPiles(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        piles_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string piles = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPiles() {
        piles_ = getDefaultInstance().getPiles();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string piles = 2;</code>
       * @param value The bytes for piles to set.
       * @return This builder for chaining.
       */
      public Builder setPilesBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        piles_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private Object opid_ = "";
      /**
       * <code>string opid = 3;</code>
       * @return The opid.
       */
      public String getOpid() {
        Object ref = opid_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          opid_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string opid = 3;</code>
       * @return The bytes for opid.
       */
      public com.google.protobuf.ByteString
          getOpidBytes() {
        Object ref = opid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          opid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string opid = 3;</code>
       * @param value The opid to set.
       * @return This builder for chaining.
       */
      public Builder setOpid(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        opid_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string opid = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearOpid() {
        opid_ = getDefaultInstance().getOpid();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string opid = 3;</code>
       * @param value The bytes for opid to set.
       * @return This builder for chaining.
       */
      public Builder setOpidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        opid_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ChargingCmd)
    }

    // @@protoc_insertion_point(class_scope:ChargingCmd)
    private static final ChargingCmd DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ChargingCmd();
    }

    public static ChargingCmd getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ChargingCmd>
        PARSER = new com.google.protobuf.AbstractParser<ChargingCmd>() {
      @Override
      public ChargingCmd parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ChargingCmd> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ChargingCmd> getParserForType() {
      return PARSER;
    }

    @Override
    public ChargingCmd getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ChargingCmd_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ChargingCmd_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021chargingCmd.proto\"7\n\013ChargingCmd\022\013\n\003cm" +
      "d\030\001 \001(\t\022\r\n\005piles\030\002 \001(\t\022\014\n\004opid\030\003 \001(\tBF\n/" +
      "com.easyit.SmartChargeStation.protocol.p" +
      "rotobufB\023ChargingCmdProtobufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ChargingCmd_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ChargingCmd_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ChargingCmd_descriptor,
        new String[] { "Cmd", "Piles", "Opid", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
